http:
  services:
    drupal:
      loadBalancer:
        servers:
          - url: http://drupal:80
  routers:
    drupal:
      rule: Host(`localhost`)
      service: drupal
    drupal-internal:
      rule: Host(`drupal.internal`)
      service: drupal
      priority: 9000
