http:
  middlewares:
    drupal-internal-host:
      headers:
        customRequestHeaders:
          Host: localhost
  services:
    drupal:
      loadBalancer:
        servers:
          - url: http://drupal:80
  routers:
    drupal:
      rule: Host(`localhost`)
      service: drupal
    drupal-internal:
      rule: Host(`drupal.internal`)
      service: drupal
      priority: 9000
      middlewares:
        - drupal-internal-host
