http:
  services:
    triplet:
      loadBalancer:
        servers:
          - url: http://triplet:8080
  routers:
    triplet:
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/iiif`)
      service: triplet
      tls: {}
