---
# Common to all services
x-common: &common
  restart: unless-stopped
  networks:
    default:
networks:
  default:

volumes:
  activemq-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  mariadb-data: {}
  solr-data: {}
  triplet-cache: {}

secrets:
  # Certificates are only used for development environments.
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  # Production secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_JMS_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"
  TOMCAT_ADMIN_PASSWORD:
    file: "./secrets/TOMCAT_ADMIN_PASSWORD"

services:
  activemq:
    <<: *common
    image: libops/activemq:5@sha256:325379229480ce585b27ccb03daa62af6c9b35996610689fe65376c56c4adef6
    secrets:
      - source: ACTIVEMQ_PASSWORD
      - source: ACTIVEMQ_WEB_ADMIN_PASSWORD
    volumes:
      - activemq-data:/opt/activemq/data:rw

  alpaca:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    image: libops/alpaca:2.4@sha256:1003499410c1fb7beee15099572347e163a305e8925d68a5c4194fde1314610a
    secrets:
      - source: ALPACA_JMS_PASSWORD
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY

    environment:
      ALPACA_FCREPO_INDEXER_ENABLED: "false"
      ALPACA_TRIPLESTORE_INDEXER_ENABLED: "false"
  crayfits:
    <<: *common
    image: libops/crayfits:main@sha256:a922ff61cdc73ae63b46d2e3b2c1e8ff41b121704aababe64f99255e274bff85
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  drupal:
    <<: *common
    build:
      context: .
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_NAME: drupal_default
      DB_USER: drupal_default
      DEVELOPMENT_ENVIRONMENT: "false"
      DRUPAL_DEFAULT_BROKER_HOST: activemq
      DRUPAL_DEFAULT_BROKER_PORT: "61613"
      DRUPAL_DEFAULT_BROKER_USER: admin
      DRUPAL_DEFAULT_BROKER_URL: tcp://activemq:61613
      DRUPAL_DEFAULT_CANTALOUPE_URL: "http://localhost/iiif/3"
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: Islandora Digital Collections
      DRUPAL_DEFAULT_PROFILE: minimal
      DRUPAL_DEFAULT_SOLR_CORE: default
      DRUPAL_DEFAULT_SOLR_HOST: solr
      DRUPAL_DEFAULT_SOLR_PORT: "8983"
      INGRESS_HOSTNAMES: "localhost,drupal.internal"
      INGRESS_SCHEME: "http"
      DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE: ""
    healthcheck:
      start_period: ${DRUPAL_HEALTHCHECK_START_PERIOD:-5m}
      retries: ${DRUPAL_HEALTHCHECK_RETRIES:-20}
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: UID
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
        target: DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: ACTIVEMQ_PASSWORD
        target: DRUPAL_DEFAULT_BROKER_PASSWORD
      - source: JWT_PRIVATE_KEY
      - source: JWT_PUBLIC_KEY
    volumes:
      - read_only: false
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        type: volume
      - read_only: false
        source: drupal-private-files
        target: /var/www/drupal/private
        type: volume
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw

  fits:
    <<: *common
    image: libops/fits:1.6.0@sha256:9471bd835e797f6c41052062c1095129748a698710df9576b8f867248e0e3b45

  homarus:
    <<: *common
    image: libops/homarus:8.1.2@sha256:e5352d9f1560bb3496fb7ff4d270085d8b05bcf61c4a2496e2e743b8eaab6fd9
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  houdini:
    <<: *common
    image: libops/houdini:8.18.2@sha256:25a40f144ba115cf08ef8dd1899fd40ee8dcd4d67bf65fd5415114dfd0ab8925
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  hypercube:
    <<: *common
    image: libops/hypercube:5.5.2@sha256:68011206c264e5e8bcb9e38fea74e6aef0319e2031f1ba71ff462144ca9bc023
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  init:
    entrypoint: /bin/bash
    command: ["-euc", "generate-certs.sh && generate-compose-secrets.sh"]
    image: libops/base:3.2.2.0@sha256:851e17742b5fee57038855f46b1a46d2716c0012c5f3a4788b7e5c7bc12fed5e
    networks:
      default:
    profiles:
      - none
    restart: "no"
    working_dir: /work
    environment:
      CA_SUBJECT: /CN=LibOps ISLE Local Development CA
      CERT_DIR: /work/certs
      COMPOSE_FILE: /work/compose.yaml
      SECRETS_ROOT: /work/secrets
      SECRET_FORMAT_DRUPAL_DEFAULT_SALT: salt74
      SUBJECT_ALT_NAMES: DNS:*.islandora.dev,DNS:islandora.dev,DNS:localhost,IP:127.0.0.1,IP:::1
    volumes:
      - ./certs:/work/certs:rw,z
      - ./secrets:/work/secrets:rw,z
      - ./compose.yaml:/work/compose.yaml:ro,z

  mariadb:
    <<: *common
    image: libops/mariadb:11.8@sha256:1b0f53f277cedf95e1fa6df25580de01dd2d0722b09f39fe0d93cfb6263e26f3
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  mergepdf:
    <<: *common
    image: islandora/mergepdf:6.3.19
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  solr:
    <<: *common
    depends_on:
      drupal:
        condition: service_healthy
    image: libops/solr:9@sha256:d4f5d06c5cba47677ba96580c1a8b524f26f93c0d05392dc287b34da9ca07d86
    volumes:
      - solr-data:/data:rw
      - read_only: false
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        type: volume
        volume:
          nocopy: true

  traefik:
    <<: *common
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.transport.respondingTimeouts.readTimeout=300s
      --providers.file.directory=/etc/traefik/dynamic
      --providers.file.watch=true
      --api.insecure=false
      --api.dashboard=false
      --api.debug=false
    depends_on:
      drupal:
        condition: service_healthy
    healthcheck:
      start_period: 10s
      test: traefik healthcheck --ping
    image: traefik:v3.7.9@sha256:652929a140a32d7cafafb13c6cdfab5376cfeff800f51397b87b524501ed02a8
    networks:
      default:
        aliases:
          - drupal.internal
    ports:
      - "80:80"
    volumes:
      - ./conf/traefik:/etc/traefik/dynamic:ro,z

  triplet:
    <<: *common
    image: ghcr.io/libops/triplet:v1.1.1@sha256:84dd6c00ed9fd3e60e4e544feda58044d1f47b624fe3a7ee2460e59cc6bf4de2
    environment:
      TRIPLET_PUBLIC_BASE_URL: http://localhost
    volumes:
      - drupal-public-files:/public:ro
      - drupal-private-files:/private:ro
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:ro,z
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:ro,z
      - triplet-cache:/var/lib/triplet/cache:rw
