---
name: isle-site-template

# Common to all services
x-common: &common
  restart: unless-stopped
  tty: true # Required for non-root users with selinux enabled.
  security_opt:
    - label=type:container_runtime_t # Required for selinux to access the docker socket and bind mount files.
  networks:
    default:
networks:
  default:

volumes:
  activemq-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  mariadb-data: {}
  solr-data: {}
  triplet-cache: {}

secrets:
  # Certificates are only used for development environments.
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  # Production secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_JMS_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"

services:
  activemq:
    <<: *common
    image: libops/activemq:5@sha256:e7bbfa1c9bc84315950a450e763794dcf8dd0cbe6029ccbc748b7d1e4f2a4b7a
    secrets:
      - source: ACTIVEMQ_PASSWORD
      - source: ACTIVEMQ_WEB_ADMIN_PASSWORD
    volumes:
      - activemq-data:/opt/activemq/data:rw

  alpaca:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    image: libops/alpaca:2.4@sha256:2df6d1889db271c44c3a91ef761835aeb25d58a87d9d72d6e6adaa564739cd26
    secrets:
      - source: ALPACA_JMS_PASSWORD
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY

    environment:
      ALPACA_FCREPO_INDEXER_ENABLED: "false"
      ALPACA_TRIPLESTORE_INDEXER_ENABLED: "false"
  crayfits:
    <<: *common
    image: libops/crayfits:main@sha256:9939b6288328e42ba8f82e79a99dd85ca4a0bb0d0f52b29466b66eaa4504e9cb
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  drupal:
    <<: *common
    build:
      args:
        REPOSITORY: libops
        TAG: nginx-1.30.3-php84
      context: .
    environment:
      DEVELOPMENT_ENVIRONMENT: "false"
      DRUPAL_DEFAULT_BROKER_HOST: activemq
      DRUPAL_DEFAULT_BROKER_PORT: "61613"
      DRUPAL_DEFAULT_BROKER_URL: tcp://activemq:61613
      DRUPAL_DEFAULT_CANTALOUPE_URL: "http://localhost/iiif/3"
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: Islandora Digital Collections
      DRUPAL_DEFAULT_PROFILE: minimal
      DRUPAL_DEFAULT_SOLR_CORE: default
      DRUPAL_DEFAULT_SOLR_HOST: solr
      DRUPAL_DEFAULT_SOLR_PORT: "8983"
      INGRESS_HOSTNAMES: "localhost,drupal.internal"
      INGRESS_SCHEME: "http"
      DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE: ""
    healthcheck:
      start_period: ${DRUPAL_HEALTHCHECK_START_PERIOD:-5m}
      retries: ${DRUPAL_HEALTHCHECK_RETRIES:-20}
    depends_on:
      mariadb:
        condition: service_healthy
    image: islandora.io/isle-site-template:local
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: UID
      - source: DB_ROOT_PASSWORD
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
        target: DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: JWT_PRIVATE_KEY
      - source: JWT_PUBLIC_KEY
    volumes:
      - read_only: false
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        type: volume
      - read_only: false
        source: drupal-private-files
        target: /var/www/drupal/private
        type: volume
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw

  fits:
    <<: *common
    image: libops/fits@sha256:f945c3aa9b1011261a038d6a2a1ddc7557d1d0c59e00add9a82a47334e78b76f

  homarus:
    <<: *common
    image: libops/homarus:8.1.2
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  houdini:
    <<: *common
    image: libops/houdini:8.18.2
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  hypercube:
    <<: *common
    image: libops/hypercube:5.5.2
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  init:
    entrypoint: /scripts/init-entrypoint.sh
    image: libops/base:3.2.2.0@sha256:01b44d543f9bc82978220a4f5151dcf2e7b794fe88b33d98cd4d4f836405aa62
    networks:
      default:
    profiles:
      - none
    restart: "no"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - ./certs:/certs:rw
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yml:/docker-compose.yml:ro
      - .:/drupal:rw
      - /var/run/docker.sock:/var/run/docker.sock:z

  mariadb:
    <<: *common
    image: libops/mariadb:11.8@sha256:7519ca636b933388a50199f3637107099cc8968db7cb535669843b1e71f7cb1b
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  mergepdf:
    <<: *common
    image: libops/mergepdf:main@sha256:8ee2a3cd7d2b02e84af559518b9f7f85e1abe87a4ee337db415619f75d2047a8
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  solr:
    <<: *common
    depends_on:
      drupal:
        condition: service_healthy
    image: libops/solr:9@sha256:7c6d97e41675f400b6d9bec461eb1ef371efcf60d7c325f227418769c44364b8
    volumes:
      - solr-data:/data:rw
      - read_only: false
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        type: volume
        volume:
          nocopy: true

  traefik:
    <<: *common
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.transport.respondingTimeouts.readTimeout=300s
      --providers.file.directory=/etc/traefik/dynamic
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      --api.insecure=false
      --api.dashboard=false
      --api.debug=false
    depends_on:
      drupal:
        condition: service_healthy
    healthcheck:
      start_period: 10s
      test: traefik healthcheck --ping
    image: traefik:v3.7.5@sha256:e4d98158c01ad752fc1071d4e9573788747230d902cdde00a772516e692d07c9
    networks:
      default:
        aliases:
          - drupal.internal
    ports:
      - "80:80"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/traefik:/etc/traefik/dynamic:ro

  triplet:
    <<: *common
    image: ghcr.io/libops/triplet:v1.1.1@sha256:84dd6c00ed9fd3e60e4e544feda58044d1f47b624fe3a7ee2460e59cc6bf4de2
    environment:
      TRIPLET_PUBLIC_BASE_URL: http://localhost
    volumes:
      - drupal-public-files:/public:ro
      - drupal-private-files:/private:ro
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:ro
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:ro
      - triplet-cache:/var/lib/triplet/cache:rw
