---
name: isle-site-template

# Common to all services
x-common: &common
  restart: unless-stopped
  tty: true # Required for non-root users with selinux enabled.
  security_opt:
    - label=type:container_runtime_t # Required for selinux to access the docker socket and bind mount files.
  networks:
    default:
networks:
  default:

volumes:
  activemq-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  mariadb-data: {}
  solr-data: {}
  triplet-cache: {}

secrets:
  # Certificates are only used for development environments.
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  # Production secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_JMS_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"

services:
  activemq:
    <<: *common
    image: libops/activemq:5
    secrets:
      - source: ACTIVEMQ_PASSWORD
      - source: ACTIVEMQ_WEB_ADMIN_PASSWORD
    volumes:
      - activemq-data:/opt/activemq/data:rw

  alpaca:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    image: libops/alpaca:2.4
    secrets:
      - source: ALPACA_JMS_PASSWORD
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY

    environment:
      ALPACA_FCREPO_INDEXER_ENABLED: "false"
      ALPACA_TRIPLESTORE_INDEXER_ENABLED: "false"
  crayfits:
    <<: *common
    image: libops/crayfits:main
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  drupal:
    <<: *common
    build:
      args:
        TAG: 1.30.3-php84
      context: .
      x-bake:
        cache-from:
          - type=registry,ref=islandora.io/isle-site-template:local
          - type=registry,ref=islandora.io/isle-site-template:latest
        cache-to:
          - type=inline
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      DEVELOPMENT_ENVIRONMENT: "true"
      DRUPAL_DEFAULT_BROKER_URL: tcp://activemq:61613
      DRUPAL_DEFAULT_CANTALOUPE_URL: "${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}/iiif/3"
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: Islandora Digital Collections
      DRUPAL_DEFAULT_PROFILE: minimal
      DRUPAL_DEFAULT_SITE_URL: ${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}
      DRUPAL_DEFAULT_SOLR_CORE: default
      DRUPAL_ENABLE_HTTPS: "false"
      DRUSH_OPTIONS_URI: ${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}
      DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE: ""
    healthcheck:
      start_period: ${DRUPAL_HEALTHCHECK_START_PERIOD:-0s}
      retries: ${DRUPAL_HEALTHCHECK_RETRIES:-3}
    image: islandora.io/isle-site-template:local
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: UID
      - source: DB_ROOT_PASSWORD
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: JWT_PRIVATE_KEY
      - source: JWT_PUBLIC_KEY
    volumes:
      - read_only: false
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        type: volume
      - read_only: false
        source: drupal-private-files
        target: /var/www/drupal/private
        type: volume
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw

  fits:
    <<: *common
    image: libops/fits:main

  homarus:
    <<: *common
    image: libops/homarus:main
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  houdini:
    <<: *common
    image: libops/houdini:main
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  hypercube:
    <<: *common
    image: libops/hypercube:main
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  init:
    entrypoint: /scripts/init-entrypoint.sh
    image: libops/base:main
    networks:
      default:
    profiles:
      - none
    restart: "no"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - ./.env:/.env
      - ./certs:/certs:rw
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yml:/docker-compose.yml:ro
      - .:/drupal:rw
      - /var/run/docker.sock:/var/run/docker.sock:z

  mariadb:
    <<: *common
    image: libops/mariadb:11.8
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  mergepdf:
    <<: *common
    image: libops/mergepdf:main
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  solr:
    <<: *common
    depends_on:
      drupal:
        condition: service_healthy
    image: libops/solr:9
    volumes:
      - solr-data:/data:rw
      - read_only: false
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        type: volume
        volume:
          nocopy: true

  traefik:
    <<: *common
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.transport.respondingTimeouts.readTimeout=300s
      --providers.file.directory=/etc/traefik/dynamic
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      --api.insecure=true
      --api.dashboard=true
      --api.debug=true
    depends_on:
      drupal:
        condition: service_healthy
    environment:
      DEVELOPMENT_ENVIRONMENT: "true"
      DOMAIN: ${DOMAIN}
      URI_SCHEME: http
    healthcheck:
      start_period: 10s
      test: traefik healthcheck --ping
    image: traefik:v3.7.5@sha256:e4d98158c01ad752fc1071d4e9573788747230d902cdde00a772516e692d07c9
    networks:
      default:
        aliases:
          - activemq.${DOMAIN}
          - blazegraph.${DOMAIN}
          - fcrepo.${DOMAIN}
          - ${DOMAIN}
          - solr.${DOMAIN}
    ports:
      - ${HOST_INSECURE_PORT:-80}:80
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/traefik:/etc/traefik/dynamic:ro

  triplet:
    <<: *common
    image: ghcr.io/libops/triplet:v1.1.1@sha256:84dd6c00ed9fd3e60e4e544feda58044d1f47b624fe3a7ee2460e59cc6bf4de2
    environment:
      TRIPLET_PUBLIC_BASE_URL: ${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}
      DOMAIN: ${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}
    volumes:
      - drupal-public-files:/public:ro
      - drupal-private-files:/private:ro
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:ro
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:ro
      - triplet-cache:/var/lib/triplet/cache:rw
