---
# Common to all services
x-common: &common
  restart: unless-stopped
  networks:
    default:
networks:
  default:

volumes:
  activemq-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  mariadb-data: {}
  solr-data: {}
  triplet-cache: {}

secrets:
  # Certificates are only used for development environments.
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  # Production secrets:
  ACTIVEMQ_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  ACTIVEMQ_WEB_ADMIN_PASSWORD:
    file: "./secrets/ACTIVEMQ_WEB_ADMIN_PASSWORD"
  ALPACA_JMS_PASSWORD:
    file: "./secrets/ACTIVEMQ_PASSWORD"
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"
  FCREPO_DB_PASSWORD:
    file: "./secrets/FCREPO_DB_PASSWORD"
  JWT_ADMIN_TOKEN:
    file: "./secrets/JWT_ADMIN_TOKEN"
  JWT_PUBLIC_KEY:
    file: "./secrets/JWT_PUBLIC_KEY"
  JWT_PRIVATE_KEY:
    file: "./secrets/JWT_PRIVATE_KEY"
  TOMCAT_ADMIN_PASSWORD:
    file: "./secrets/TOMCAT_ADMIN_PASSWORD"

services:
  activemq:
    <<: *common
    image: libops/activemq:5@sha256:9907574809fc3bb2bb8dfa0f59e750b166e01586ae53968fbfcdeacd003d0146
    secrets:
      - source: ACTIVEMQ_PASSWORD
      - source: ACTIVEMQ_WEB_ADMIN_PASSWORD
    volumes:
      - activemq-data:/opt/activemq/data:rw

  alpaca:
    <<: *common
    depends_on:
      activemq:
        condition: service_healthy
    image: libops/alpaca:2.4@sha256:8af69239f2e957abc70fd103bb05832ac0f80bc52b83b64258472c538d0b87e6
    secrets:
      - source: ALPACA_JMS_PASSWORD
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY

    environment:
      ALPACA_FCREPO_INDEXER_ENABLED: "false"
      ALPACA_TRIPLESTORE_INDEXER_ENABLED: "false"
  crayfits:
    <<: *common
    image: libops/crayfits:main@sha256:a6178116cfe8a535d2321ef043159895a46aef19714449579d3347fa5e139b69
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  drupal:
    <<: *common
    build:
      context: .
    environment:
      DEVELOPMENT_ENVIRONMENT: "false"
      DRUPAL_DEFAULT_BROKER_HOST: activemq
      DRUPAL_DEFAULT_BROKER_PORT: "61613"
      DRUPAL_DEFAULT_BROKER_USER: admin
      DRUPAL_DEFAULT_BROKER_URL: tcp://activemq:61613
      DRUPAL_DEFAULT_CANTALOUPE_URL: "http://localhost/iiif/3"
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: Islandora Digital Collections
      DRUPAL_DEFAULT_PROFILE: minimal
      DRUPAL_DEFAULT_SOLR_CORE: default
      DRUPAL_DEFAULT_SOLR_HOST: solr
      DRUPAL_DEFAULT_SOLR_PORT: "8983"
      INGRESS_HOSTNAMES: "localhost,drupal.internal"
      INGRESS_SCHEME: "http"
      DRUPAL_DEFAULT_TRIPLESTORE_NAMESPACE: ""
    healthcheck:
      start_period: ${DRUPAL_HEALTHCHECK_START_PERIOD:-5m}
      retries: ${DRUPAL_HEALTHCHECK_RETRIES:-20}
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: UID
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
        target: DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: ACTIVEMQ_PASSWORD
        target: DRUPAL_DEFAULT_BROKER_PASSWORD
      - source: JWT_PRIVATE_KEY
      - source: JWT_PUBLIC_KEY
    volumes:
      - read_only: false
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        type: volume
      - read_only: false
        source: drupal-private-files
        target: /var/www/drupal/private
        type: volume
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw

  fits:
    <<: *common
    image: libops/fits:1.6.0@sha256:f1debfe52827a18ef3d02224cff683477dfb9073307bf4000739c7627a08c6d5

  homarus:
    <<: *common
    image: libops/homarus:8.1.2@sha256:f3a826a80a7f44f0a4245ac9647c05ab509f19c9b991d6f71a263adadbeae7dd
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  houdini:
    <<: *common
    image: libops/houdini:8.18.2@sha256:a78854fbaedfe8793c7e90ee170c301bc15139022e571944c396b146b57ec821
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  hypercube:
    <<: *common
    image: libops/hypercube:5.5.2@sha256:ac162e3b483c18678e764b994fe91a4558bbb7011223145d8d9d51b5a1165356
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  init:
    entrypoint: /scripts/init-entrypoint.sh
    image: libops/base:3.2.2.0@sha256:d4da77a62c6dead3d52c0e0cc4f38647379d7edd8b2be7b17a2cce06d469b545
    networks:
      default:
    profiles:
      - none
    restart: "no"
    volumes:
      - ./certs:/certs:rw,z
      - ./secrets:/secrets:rw,z
      - ./scripts:/scripts:ro,z
      - ./docker-compose.yml:/docker-compose.yml:ro,z

  mariadb:
    <<: *common
    image: libops/mariadb:11.8@sha256:7e0eb90c7cba204b62e8bed72fba00193cbc2e50072fc6e40a6fab8de4b0b857
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  mergepdf:
    <<: *common
    image: islandora/mergepdf:6.4.3@sha256:fcd7c2e81a67df773d5acbcbf6d307e1552f46722591ddeaf8f949b42ae2c97d
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_ADMIN_TOKEN
      - source: JWT_PUBLIC_KEY

  solr:
    <<: *common
    depends_on:
      drupal:
        condition: service_healthy
    image: libops/solr:9@sha256:089ab7c43efcba365b29de1f55ddc58e740659c120c9317e30c5881100001761
    volumes:
      - solr-data:/data:rw
      - read_only: false
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        type: volume
        volume:
          nocopy: true

  traefik:
    <<: *common
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.transport.respondingTimeouts.readTimeout=300s
      --providers.file.directory=/etc/traefik/dynamic
      --providers.file.watch=true
      --api.insecure=false
      --api.dashboard=false
      --api.debug=false
    depends_on:
      drupal:
        condition: service_healthy
    healthcheck:
      start_period: 10s
      test: traefik healthcheck --ping
    image: traefik:v3.7.9@sha256:652929a140a32d7cafafb13c6cdfab5376cfeff800f51397b87b524501ed02a8
    networks:
      default:
        aliases:
          - drupal.internal
    ports:
      - "80:80"
    volumes:
      - ./conf/traefik:/etc/traefik/dynamic:ro,z

  triplet:
    <<: *common
    image: ghcr.io/libops/triplet:v1.2.0@sha256:6f7ce5374a4517456ae0b8ba410f0abd2e6a717675e8f4e3e18ddf6ab2227ace
    environment:
      TRIPLET_PUBLIC_BASE_URL: http://localhost
    volumes:
      - drupal-public-files:/public:ro
      - drupal-private-files:/private:ro
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:ro,z
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:ro,z
      - triplet-cache:/var/lib/triplet/cache:rw
