SHELL := /bin/bash

.PHONY: help init up clean reconcile healthcheck test demo-objects sync-solr-conf create-starter-site-pr
.SILENT:

-include custom.Makefile

help: ## Show this help message
	echo 'Usage: make [target]'
	echo ''
	echo 'Available targets:'
	awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%s\033[0m\t%s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort | column -t -s $$'\t'

clean: ## Delete stateful local data generated by the template
	sitectl compose clean

init reconcile: ## Generate or repair declared initialization state
	sitectl compose reconcile

up: ## Start the complete site and wait for health
	sitectl compose up --wait

healthcheck: ## Check Compose and application health
	sitectl healthcheck

test: ## Run the full ISLE template smoke test
	./scripts/test.sh

demo-objects: ## Add demo objects from https://github.com/Islandora-Devops/islandora_demo_objects
	./scripts/demo-objects.sh

sync-solr-conf: ## Refresh tracked Solr default core config from the running drupal container
	sitectl drupal solr-config refresh

create-starter-site-pr: ## Create a PR for islandora-starter-site updates
	./scripts/create-pr.sh
