SHELL := /bin/bash

.PHONY: help clean demo-objects overwrite-starter-site sync-solr-conf create-starter-site-pr
.SILENT:

-include custom.Makefile

help: ## Show this help message
	echo 'Usage: make [target]'
	echo ''
	echo 'Available targets:'
	awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%s\033[0m\t%s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort | column -t -s $$'\t'

clean: ## Delete stateful local data generated by the template
	./scripts/clean.sh

demo-objects: ## Add demo objects from https://github.com/Islandora-Devops/islandora_demo_objects
	./scripts/demo-objects.sh

overwrite-starter-site: ## Keep site template's Drupal install in sync with islandora-starter-site
	./scripts/overwrite-starter-site.sh

sync-solr-conf: ## Refresh tracked Solr default core config from the running drupal container
	./scripts/sync-solr-conf.sh

create-starter-site-pr: ## Create a PR for islandora-starter-site updates
	./scripts/create-pr.sh
